DROP TABLE IF EXISTS work.pubmedT32_master;
create table work.pubmedT32_master as
select * from work.PubmedT32 ;


DROP tABLE IF EXISTS work.pubmedT32_undup; 
Create table work.pubmedT32_undup AS
SELECT PMID,PMCID,max(Citation) as Citation
from work.pubmedT32_master
GROUP BY PMID,PMCID;

ALTER TABLE work.pubmedT32_undup
ADD SomeMatch int(1);

SET SQL_SAFE_UPDATES = 0;
UPDATE work.pubmedT32_undup SET SomeMatch=0;

 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Abrantes A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ajayi T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Albizu A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Aldrich J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Allen R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ashby III F',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ayomen E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bailey O',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Beliakoff R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bell K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Benevides E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bermudez E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Besosa C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bolandparvaz A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bolen M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Boles J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Boutzoukas E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Brown Fedenko S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Brumley D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Brunson D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Bu M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Burke M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Carter M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Chang M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Charles A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Chiu Lam A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Cohen S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Cooper T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Cushion M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Da Silva D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Deaterly C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Di M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Diaz B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Dicola N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Dougherty M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Dumeny L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Dyson K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ebeid M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ellis E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Elsadek L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Engelbrecht A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Erwin N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Evangelista N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Falise A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Fisk-Hoffman R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Flohr R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Francis C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Freeman B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Fuller E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Fusco A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Garcia C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Gawronski B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Gbadamosi M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Gillett D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Golliher H',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Gonzalez K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Good H',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Goodwin Z',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Gopinath A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Grams T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Greenberg Z',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Guenther D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Hardcastle C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Harriman R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Harrison N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Hausman H',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Helm E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Heon M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Hernandez M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Herrick M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Hewitt L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Huber M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Imhoff E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ivankovic-MacGibbon F',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Jernigan J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Johnson N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Katrak C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Kennedy J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Kirkpatrick K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Kraft J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Kulkarni S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Langer K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Lightsey S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ligocki A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Lipat A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Lloyd G',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Lovelace T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Lynch A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Mackie P',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Makarem M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Mamallapalli J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Mancera Azamar K',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Marchi F',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Mark J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Marrero R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('McLaren C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Mcmillan B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Miller D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Monjure T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Montalvo A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Moore A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Morales Aparicio J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Morales Rivera A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Munzen M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nelson T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Newport R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Newsome R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nguyen B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nguyen L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nguyen N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nourie L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nozka A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Nutley S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ortiz T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Pacifi N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Parisi C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Paterno G',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Payton I',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Peiper A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Peterson A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Phan L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Price J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Pyon W',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Quintin S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rakestraw N',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rich S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Richards V',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rijos E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rivera Rodriguez A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rivera-Llabres V',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Roach T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ross A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Rubin G',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Sajdeya R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Schoppee T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Seedansingh J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Shapiro M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Simon Z',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Singer M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Singh I',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Smith A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Smith C',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Smith E',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Smith S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Sniffen S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Solone X',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Stafford L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Staley H',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Stottlemire B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Stribling D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Strickland Z',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Temples M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Tewolde F',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Thompson S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Tomas R',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Torrellas J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Torres S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Tu A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Ulm B',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Vargas A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Velazquez-Albino A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Vinson A',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Wallace-Farquharson T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Williams M',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Williams T',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Winders S',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Xia Y',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Yang L',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Yuan D',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Zakrzewski J',Citation)<>0;
 UPDATE work.pubmedT32_undup set SomeMatch=1 WHERE Locate('Zequeira S',Citation)<>0;




SELECT sum(SomeMatch) from work.pubmedT32_undup;

DROP TABLE IF EXISTS work.t32CoreMatch;
Create table work.t32CoreMatch as
SELECT * from work.pubmedT32_undup
WHERE SomeMatch=1;

ALTER TABLE work.t32CoreMatch
ADD ScholarName varchar(35);

###Create blank Structure
drop table if Exists work.t32Scholarpub;
CREATE TABLE work.t32Scholarpub as
SELECT * 
FROM work.t32CoreMatch LIMIT 0;

UPDATE work.t32CoreMatch SET ScholarName=NULL;

UPDATE work.t32CoreMatch Set ScholarName='Abrantes, Anthony' WHERE Locate('Abrantes A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ajayi, Tolulope' WHERE Locate('Ajayi T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Albizu, Alejandro' WHERE Locate('Albizu A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Aldrich, Jessica' WHERE Locate('Aldrich J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Allen, Riley' WHERE Locate('Allen R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ashby III, Frederick' WHERE Locate('Ashby III F',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ayomen, Estelle' WHERE Locate('Ayomen E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bailey, Olivia' WHERE Locate('Bailey O',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Beliakoff, Reagan' WHERE Locate('Beliakoff R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bell, Kristina' WHERE Locate('Bell K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Benevides, Ethan' WHERE Locate('Benevides E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bermudez, Esteban' WHERE Locate('Bermudez E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Besosa, Cristina' WHERE Locate('Besosa C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bolandparvaz, Amirhossain' WHERE Locate('Bolandparvaz A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bolen, Mackenzie' WHERE Locate('Bolen M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Boles, Jake' WHERE Locate('Boles J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Boutzoukas, Emanuel' WHERE Locate('Boutzoukas E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Brown Fedenko, Shannon' WHERE Locate('Brown Fedenko S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Brumley, David' WHERE Locate('Brumley D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Brunson, Debra' WHERE Locate('Brunson D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Bu, Mengfei' WHERE Locate('Bu M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Burke, Matthew' WHERE Locate('Burke M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Carter, Miranda' WHERE Locate('Carter M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Chang, Minji' WHERE Locate('Chang M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Charles, Angel' WHERE Locate('Charles A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Chiu Lam, Andreina' WHERE Locate('Chiu Lam A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Cohen, Scott' WHERE Locate('Cohen S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Cooper, Tara' WHERE Locate('Cooper T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Cushion, Minor' WHERE Locate('Cushion M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Da Silva, Danilo' WHERE Locate('Da Silva D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Deaterly, Caroline' WHERE Locate('Deaterly C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Di, Marissa' WHERE Locate('Di M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Diaz, Brian' WHERE Locate('Diaz B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Dicola, Nicholas' WHERE Locate('Dicola N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Dougherty, Michael' WHERE Locate('Dougherty M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Dumeny, Leanne' WHERE Locate('Dumeny L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Dyson, Kyle' WHERE Locate('Dyson K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ebeid, Mark' WHERE Locate('Ebeid M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ellis, Emma' WHERE Locate('Ellis E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Elsadek, Lobna' WHERE Locate('Elsadek L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Engelbrecht, Avery' WHERE Locate('Engelbrecht A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Erwin, Nina' WHERE Locate('Erwin N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Evangelista, Nicole' WHERE Locate('Evangelista N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Falise, Alyssa' WHERE Locate('Falise A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Fisk-Hoffman, Rebecca' WHERE Locate('Fisk-Hoffman R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Flohr, Rylie' WHERE Locate('Flohr R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Francis, Connor' WHERE Locate('Francis C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Freeman, Breanne' WHERE Locate('Freeman B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Fuller, Eric' WHERE Locate('Fuller E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Fusco, Anna' WHERE Locate('Fusco A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Garcia, Christian C' WHERE Locate('Garcia C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Gawronski, Brian' WHERE Locate('Gawronski B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Gbadamosi, Mohammed' WHERE Locate('Gbadamosi M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Gillett, Drew' WHERE Locate('Gillett D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Golliher, Hannah' WHERE Locate('Golliher H',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Gonzalez, Katherine' WHERE Locate('Gonzalez K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Good, Hayden' WHERE Locate('Good H',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Goodwin, Zakia' WHERE Locate('Goodwin Z',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Gopinath, Adithya' WHERE Locate('Gopinath A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Grams, Tristan' WHERE Locate('Grams T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Greenberg, Zachary' WHERE Locate('Greenberg Z',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Guenther, Dylan' WHERE Locate('Guenther D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Hardcastle, Cheshire' WHERE Locate('Hardcastle C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Harriman, Rian' WHERE Locate('Harriman R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Harrison, Natalie' WHERE Locate('Harrison N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Hausman, Hanna' WHERE Locate('Hausman H',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Helm, Emily' WHERE Locate('Helm E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Heon, Mikala' WHERE Locate('Heon M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Hernandez, Maria' WHERE Locate('Hernandez M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Herrick, Mary' WHERE Locate('Herrick M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Hewitt, Leeann' WHERE Locate('Hewitt L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Huber, Mollie' WHERE Locate('Huber M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Imhoff, Eric' WHERE Locate('Imhoff E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ivankovic-MacGibbon, Franjo' WHERE Locate('Ivankovic-MacGibbon F',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Jernigan, Janna' WHERE Locate('Jernigan J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Johnson, Natalie' WHERE Locate('Johnson N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Katrak, Callahan' WHERE Locate('Katrak C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Kennedy, Jack' WHERE Locate('Kennedy J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Kirkpatrick, Kelly' WHERE Locate('Kirkpatrick K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Kraft, Jessica' WHERE Locate('Kraft J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Kulkarni, Shweta' WHERE Locate('Kulkarni S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Langer, Kailey' WHERE Locate('Langer K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Lightsey, Suzanne' WHERE Locate('Lightsey S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ligocki, Alexander' WHERE Locate('Ligocki A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Lipat, Ania' WHERE Locate('Lipat A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Lloyd, Grace' WHERE Locate('Lloyd G',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Lovelace, Tyler' WHERE Locate('Lovelace T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Lynch, Allison' WHERE Locate('Lynch A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Mackie, Phillip' WHERE Locate('Mackie P',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Makarem, Mariana' WHERE Locate('Makarem M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Mamallapalli, Jessica' WHERE Locate('Mamallapalli J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Mancera Azamar, Karen' WHERE Locate('Mancera Azamar K',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Marchi, Francisco' WHERE Locate('Marchi F',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Mark, Julian' WHERE Locate('Mark J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Marrero, Richard' WHERE Locate('Marrero R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='McLaren, Christian' WHERE Locate('McLaren C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Mcmillan, Brian' WHERE Locate('Mcmillan B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Miller, Douglas' WHERE Locate('Miller D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Monjure, Tia' WHERE Locate('Monjure T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Montalvo, Abelardo' WHERE Locate('Montalvo A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Moore, Andrew' WHERE Locate('Moore A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Morales Aparicio, Joyce' WHERE Locate('Morales Aparicio J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Morales Rivera, Adriana' WHERE Locate('Morales Rivera A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Munzen, Melissa' WHERE Locate('Munzen M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nelson, Tarah' WHERE Locate('Nelson T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Newport, Rylee' WHERE Locate('Newport R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Newsome, Rachel' WHERE Locate('Newsome R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nguyen, Binh' WHERE Locate('Nguyen B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nguyen, Long' WHERE Locate('Nguyen L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nguyen, Nam' WHERE Locate('Nguyen N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nourie, Luke' WHERE Locate('Nourie L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nozka, Aniela' WHERE Locate('Nozka A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Nutley, Sara' WHERE Locate('Nutley S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ortiz, Tala' WHERE Locate('Ortiz T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Pacifi, Noah' WHERE Locate('Pacifi N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Parisi, Christina' WHERE Locate('Parisi C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Paterno, Giavanna' WHERE Locate('Paterno G',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Payton, Isaac' WHERE Locate('Payton I',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Peiper, Amy' WHERE Locate('Peiper A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Peterson, Alexandra' WHERE Locate('Peterson A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Phan, Leah' WHERE Locate('Phan L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Price, Julianne' WHERE Locate('Price J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Pyon, Wonn' WHERE Locate('Pyon W',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Quintin, Stephan' WHERE Locate('Quintin S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rakestraw, Noah' WHERE Locate('Rakestraw N',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rich, Shannan' WHERE Locate('Rich S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Richards, Veronica' WHERE Locate('Richards V',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rijos, Eddy' WHERE Locate('Rijos E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rivera Rodriguez, Angelie' WHERE Locate('Rivera Rodriguez A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rivera-Llabres, Victor' WHERE Locate('Rivera-Llabres V',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Roach, Tracoyia' WHERE Locate('Roach T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ross, Aleyna' WHERE Locate('Ross A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Rubin, Garret' WHERE Locate('Rubin G',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Sajdeya, Ruba' WHERE Locate('Sajdeya R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Schoppee, Tasha' WHERE Locate('Schoppee T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Seedansingh, Johleen' WHERE Locate('Seedansingh J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Shapiro, Melanie' WHERE Locate('Shapiro M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Simon, Zachary' WHERE Locate('Simon Z',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Singer, Michele' WHERE Locate('Singer M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Singh, Ishita' WHERE Locate('Singh I',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Smith, Alexis' WHERE Locate('Smith A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Smith, Clinton' WHERE Locate('Smith C',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Smith, Ethan' WHERE Locate('Smith E',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Smith, Samantha' WHERE Locate('Smith S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Sniffen, Sarah' WHERE Locate('Sniffen S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Solone, Xzaviar' WHERE Locate('Solone X',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Stafford, Lauren' WHERE Locate('Stafford L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Staley, Hannah' WHERE Locate('Staley H',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Stottlemire, Bryce' WHERE Locate('Stottlemire B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Stribling, Daniel' WHERE Locate('Stribling D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Strickland, Zachary' WHERE Locate('Strickland Z',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Temples, Madison' WHERE Locate('Temples M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Tewolde, Furtuna' WHERE Locate('Tewolde F',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Thompson, Sharon' WHERE Locate('Thompson S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Tomas, Rodrigo' WHERE Locate('Tomas R',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Torrellas, Jose' WHERE Locate('Torrellas J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Torres, Soleil' WHERE Locate('Torres S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Tu, Allen' WHERE Locate('Tu A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Ulm, Brittany' WHERE Locate('Ulm B',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Vargas, Ana' WHERE Locate('Vargas A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Velazquez-Albino, Ambar' WHERE Locate('Velazquez-Albino A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Vinson, Augustine' WHERE Locate('Vinson A',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Wallace-Farquharson, Tanya' WHERE Locate('Wallace-Farquharson T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Williams, Mackenzie' WHERE Locate('Williams M',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Williams, Tristan' WHERE Locate('Williams T',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Winders, Samantha' WHERE Locate('Winders S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Xia, Yuxing' WHERE Locate('Xia Y',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Yang, Lilia' WHERE Locate('Yang L',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Yuan, Daniel' WHERE Locate('Yuan D',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Zakrzewski, Jessica' WHERE Locate('Zakrzewski J',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;
UPDATE work.t32CoreMatch Set ScholarName='Zequeira, Sabrina' WHERE Locate('Zequeira S',Citation)<>0;   INSERT INTO work.t32Scholarpub SELECT * FROM work.t32CoreMatch WHERE ScholarName is Not Null;  UPDATE work.t32CoreMatch SET ScholarName=NULL;

 select count(*) from work.t32Scholarpub;
 select * from work.t32Scholarpub;

## SUMMARIZE RANGE
Drop table if exists work.T32raqngeUndup;
create table work.T32raqngeUndup As 
select Trainee_Name, min(`From`) as StartDate, Max(`To`) as Enddate from work.t32range group by Trainee_Name ;


Drop table if exists work.T32PMcnt;
create table work.T32PMcnt As 
SELECT ScholarName,count(distinct PMID) as nPubs from work.t32Scholarpub group by ScholarName order by ScholarName ;





