DROP TABLE IF EXISTS work.covid_award_detail;
Create table work.covid_award_detail AS
select 	CLK_AWD_ID,
		CLK_AWD_STATE,
        CLK_AWD_PI,
        CLK_AWD_PROJ_NAME,
        REPORTING_SPONSOR_NAME,
        CLK_AWD_FULL_TITLE,
        REPORTING_SPONSOR_CAT,
        REPORTING_SPONSOR_AWD_ID,
        DIRECT_AMOUNT,
        INDIRECT_AMOUNT,
        SPONSOR_AUTHORIZED_AMOUNT,
        FUNDS_ACTIVATED,
        CLK_AWD_PROJ_MGR
from lookup.awards_history
WHERE 	(LOCATE("COVID",CLK_AWD_PROJ_NAME)<>0 OR
		 LOCATE("COVID",CLK_AWD_FULL_TITLE)<>0)
  AND    LOCATE('Covidien',CLK_AWD_PROJ_NAME)=0
  AND    LOCATE('Covidence',CLK_AWD_PROJ_NAME)=0
  ;
  

DROP TABLE IF EXISTS  work.covid_award_summary;  
Create table work.covid_award_summary AS
select 	CLK_AWD_ID,
		max(CLK_AWD_PROJ_NAME) AS CLK_AWD_PROJ_NAME,
        MAX(CLK_AWD_PI) AS PI,
        MAX(REPORTING_SPONSOR_NAME) AS REPORTING_SPONSOR_NAME,
        max(FUNDS_ACTIVATED) AS FUNDS_ACTIVATED,
         SUM(SPONSOR_AUTHORIZED_AMOUNT) AS Total_AMT,
        MAX(CLK_AWD_FULL_TITLE) AS CLK_AWD_FULL_TITLE,
        MAX(REPORTING_SPONSOR_CAT) AS REPORTING_SPONSOR_CAT,
        MAX(REPORTING_SPONSOR_AWD_ID) AS REPORTING_SPONSOR_AWD_ID,
        SUM(DIRECT_AMOUNT) AS DIRECT_AMOUNT,
        SUM(INDIRECT_AMOUNT) AS INDIRECT_AMOUNT
from lookup.awards_history
WHERE 	(LOCATE("COVID",CLK_AWD_PROJ_NAME)<>0 OR
		 LOCATE("COVID",CLK_AWD_FULL_TITLE)<>0)
  AND    LOCATE('Covidien',CLK_AWD_PROJ_NAME)=0
  AND    LOCATE('Covidence',CLK_AWD_PROJ_NAME)=0
GROUP BY CLK_AWD_ID  ;
  