DROP TABLe IF EXISTS work.fedcovid;
Create table work.fedcovid AS
select CLK_AWD_ID,
		MAX(CLK_AWD_PI) AS CLK_AWD_PI,
        MAX(CLK_PI_UFID) AS CLK_PI_UFID ,
        MAX(CLK_AWD_FULL_TITLE) AS Title,
        MAX(REPORTING_SPONSOR_NAME) as REPORTING_SPONSOR_NAME,
        MAX(REPORTING_SPONSOR_AWD_ID) AS REPORTING_SPONSOR_AWD_ID,
        SUM(DIRECT_AMOUNT) AS DIRECT_AMOUNT,
        SUM(INDIRECT_AMOUNT) As INDIRECT_AMOUNT,
        SUM(SPONSOR_AUTHORIZED_AMOUNT) AS SPONSOR_AUTHORIZED_AMOUNT,
        MIN(FUNDS_ACTIVATED) AS FUNDS_ACTIVATED
 from lookup.awards_history
WHERE REPORTING_SPONSOR_CAT="Federal Agencies"
AND (	CLK_AWD_FULL_TITLE LIKE "%COVID%" )
GROUP BY CLK_AWD_ID
        ;
        
        

