
DROP TABLE IF EXISTS work.act_R01;
CREATE TABLE work.act_R01 AS
SELECT CLK_AWD_ID,
       CLK_AWD_PI,
       CLK_PI_UFID,
	MAX(CLK_AWD_PRIME_SPONSOR_NAME) AS Sponsor,
	MAX(CLK_AWD_PRIME_SPONSOR_AWD_ID) AS Sponsor_Award,
	MAX(CLK_AWD_FULL_TITLE) AS Title,
	MIN(CLK_AWD_OVERALL_START_DATE) AS StartDate,
	MAX(CLK_AWD_OVERALL_END_DATE) AS EndDate
FROM lookup.awards_history
WHERE CLK_AWD_PRIME_SPONSOR_NAME LIKe  "NATL INST OF HLTH%"
AND CLK_AWD_PRIME_SPONSOR_AWD_ID LIKE "%R01%"
AND CLK_AWD_OVERALL_END_DATE>=CURDATE()
GROUP BY  CLK_AWD_ID,
       CLK_AWD_PI,
       CLK_PI_UFID;

ALter table work.act_R01 ADD PI_EMAIL varchar(120);

SET SQL_SAFE_UPDATES = 0;

CREATE INDEX emailufid ON lookup.email (UF_UFID);

UPDATE work.act_R01 r1, lookup.email lu
SET r1.PI_EMAIL=lu.UF_EMAIL
WHERE r1.CLK_PI_UFID=lu.UF_UFID;

UPDATE work.act_R01 SET PI_EMAIL="Samir.Shah@surgery.ufl.edu" WHere clk_pi_ufid='16919979';

