select [CLK_PROPOSAL_ID],
[CLK_PRO_DATE_SUBMITTED],
[CLK_PI_UFID],
[CLK_PI_NAME],
[CLK_DESCRIPTION],
[CLK_CURRENTSTATE],
[CLK_SPONSOR_AWARD_ID],
[CLK_SPONSOR_ID],
[CLK_PRIMARY_SPONSOR_ID],
[CLK_PRIMARY_SPONSOR_NAME],
[CLK_PRIMARY_SPONSOR_CAT],
[CLK_REPORTING_SPONSOR_ID],
[CLK_REPORTING_SPONSOR_CATEGORY],
[CLK_TOTAL_DIRECT_COSTS],
[CLK_GRAND_TOTAL],
[CLK_TOTAL_DIRECT_COSTSHARE],
[CLK_TOTAL_INDIRECT_COSTSHARE],
[CLK_GRAND_TOTAL_COSTSHARE],
[CLK_GRAND_TOTAL_CS_ORIGSUBM],
[CLK_TOTAL_DIRECT_CS_ORIGSUBM],
[CLK_TOTAL_INDIRECT_CS_ORIGSUBM],
[CLK_TOTAL_DIRECT_ORIGSUBM],
[CLK_TOTAL_INDIRECT_ORIGSUBM],
[CLK_HUMAN_SUBJECTS],
[CLK_LAB_ANIMALS],
[CLK_CLINICAL_SERVICES_REQUIRED],
[CLK_INST_TRAIN_GRANT],
[CLK_KEYWORDS],
[CLK_IRB_STATUS],
[CLK_IRB_APPV],
[CLK_IRB_PROTOCOL_NUM],
[CLK_IACUC_STATUS],
[CLK_IACUC_APPV]
from [IS_BaseData].[Base].[vwWH_CLICK_PROPOSAL_DETAIL]
WHERE [CLK_PI_UFID] IN ('36331583','52967971');

WHERE [CLK_PRO_DATE_SUBMITTED]>='01/01/2017 12:00:00 AM';


