
USE ctsi_webcamp_pr;

DROP TABLE IF EXISTS ctsi_webcamp_adhoc.LizSQL;
CREATE TABLE ctsi_webcamp_adhoc.LizSQL AS

SELECT LABTEST.LABTEST,PERSON.LASTNAME,PERSON.FIRSTNAME,CORESERVICE.STARTDATE,DEFAULTCOST,QUANTITY_OF_SERVICE,DEFAULTCOST*QUANTITY_OF_SERVICE AS AmountDue
FROM (((((CORESERVICE INNER JOIN LABTEST ON CORESERVICE.LABTEST=LABTEST.UNIQUEFIELD)
                   LEFT OUTER JOIN (SELECT MAX(UNIQUEFIELD) AS CurrUF,LABTEST FROM LABTESTCOST GROUP BY LABTEST) AS LastCostRec ON LastCostRec.LABTEST=LABTEST.UNIQUEFIELD)
                    LEFT OUTER JOIN LABTESTCOST ON LABTESTCOST.UNIQUEFIELD=LastCostRec.CurrUF)
                  LEFT OUTER JOIN CORESERVICE_PERSONPROVIDER ON CORESERVICE_PERSONPROVIDER.CORESERVICE=CORESERVICE.UNIQUEFIELD)
                  INNER JOIN PERSON ON CORESERVICE_PERSONPROVIDER.PERSON=PERSON.UNIQUEFIELD);
